before:
  hooks:
    - go mod tidy -v
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm
      - arm64
      - 386
      - amd64
      - mips
      - mipsle
      - s390x
      - riscv64
    gomips:
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: .
    binary: nb
universal_binaries:
  - name_template: "nb"
    replace: false
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "nb"
archives:
  - name_template: "nb_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - nb.yaml
      - README.md
      - LICENSE
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge branch
      - go mod tidy
