banner: |
  {{ .AnsiColor.Green }}
  ============     naiba's workflow     ============
  {{ .AnsiColor.Red }}
      ███▄    █  ▄▄▄       ██▓ ▄▄▄▄    ▄▄▄
      ██ ▀█   █ ▒████▄    ▓██▒▓█████▄ ▒████▄
     ▓██  ▀█ ██▒▒██  ▀█▄  ▒██▒▒██▒ ▄██▒██  ▀█▄ 
     ▓██▒  ▐▌██▒░██▄▄▄▄██ ░██░▒██░█▀  ░██▄▄▄▄██
     ▒██░   ▓██░ ▓█   ▓██▒░██░░▓█  ▀█▓ ▓█   ▓██▒
     ░ ▒░   ▒ ▒  ▒▒   ▓▒█░░▓  ░▒▓███▀▒ ▒▒   ▓▒█░
     ░ ░░   ░ ▒░  ▒   ▒▒ ░ ▒ ░▒░▒   ░   ▒   ▒▒ ░
        ░   ░ ░   ░   ▒    ▒ ░ ░    ░   ░   ▒
              ░       ░  ░ ░   ░            ░  ░
                                    ░
  {{ .AnsiColor.Green }}============ Now: {{ .Now "Monday, 2 Jan 2006" }} ============
  {{ .AnsiColor.Green }}
